version: "2"

services:
  glpi:
    environment:
      - GLPI_VERSION=${GLPI_VERSION}
      - GLPI_upload_max_filesize=${GLPI_upload_max_filesize}
      - GLPI_post_max_size=${GLPI_post_max_size}
      - GLPI_memory_limit=${GLPI_memory_limit}
      - GLPI_max_execution_time=${GLPI_max_execution_time}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - HTTPS_PROXY=${HTTPS_PROXY}
    build:
      context: glpi
      dockerfile: Dockerfile
    privileged: true
    hostname: glpi
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "${GLPI_PATH}/html:/var/www/html"
      - "${GLPI_PATH}/logs/apache2:/var/log/apache2"
    container_name: "${GLPI_NAME}_glpi"
    links:
      - mysql:mysql
    ports:
      -  "${GLPI_HTTP_IP_PORT}:80"
    depends_on:
      - mysql
    restart: always

#    logging:
#      driver: none

  mysql:
    image: mysql:5.7
    volumes:
      - "${GLPI_PATH}/mysql_data:/var/lib/mysql"
      - "${GLPI_PATH}/mysql_backup:/mysql_backup"
    restart: always
    container_name: "${GLPI_NAME}_mysql"
    env_file:
      - ./.env


