version: '2'
services:
  linuxserver-letsencrypt:
    image: linuxserver/letsencrypt
    container_name: "${GLPI_NAME}_letsencrypt"
    hostname: letsencrypt
    ports:
      - "${LETS_HTTP_IP_PORT}:80"
      - "${LETS_HTTPS_IP_PORT}:443"
    restart: on-failure:1
    volumes:
      - ${GLPI_PATH}/letsencrypt/config:/config
#      - ${GLPI_PATH}/letsencrypt/nginx.conf:/config/nginx/site-confs/default
    depends_on:
      - glpi
    environment:
      - EMAIL=${LETS_EMAIL}
      - URL=${LETS_URL}
      - SUBDOMAINS=${LETS_SUBDOMAIN}
      - ONLY_SUBDOMAINS=true
      - VALIDATION=http
      - TZ=Europe/Moscow
      - PGID=abc
      - PUID=abc
   # - STAGING=true # this should be uncommented when testing for initial success, to avoid some rate limiting

