version: '2'
services:
  linuxserver-letsencrypt:
    image: linuxserver/letsencrypt
    container_name: "${GLPI_NAME}_letsencrypt"
    hostname: letsencrypt
    ports:
      - "${LETS_HTTP_IP_PORT}:80"
      - "${LETS_HTTPS_IP_PORT}:443"
    restart: on-failure:1
    volumes:
      - ${GLPI_PATH}/letsencrypt/config:/config
      - ${GLPI_PATH}/nginx-sites:/config/nginx/site-confs:ro
    environment:
      - EMAIL=${LETS_EMAIL}
#      - URL=${LETS_DOMAIN}
      - URL=erchov.ru
      - SUBDOMAINS=glpi
      - VALIDATION=http
      - TZ=Europe/Moscow
      - PGID=0
      - PUID=0
#      - /etc/localtime:/etc/localtime:ro
#      UPSTREAM: "registry:80"
#      - UPSTREAM: "192.168.100.240:85"


