version: '2'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - "${GLPI_PATH}/mysql_data:/var/lib/mysql"
    restart: always
    container_name: "${GLPI_NAME}_mysql"
    env_file:
      - ./mysql.env
    logging:
      driver: none

  glpi:
    environment:
      - GLPI_VERSION=${GLPI_VERSION}
      - GLPI_upload_max_filesize=${GLPI_upload_max_filesize}
      - GLPI_post_max_size=${GLPI_post_max_size}
      - GLPI_memory_limit=${GLPI_memory_limit}
      - GLPI_max_execution_time=${GLPI_max_execution_time}
    build:
      context: glpi
      dockerfile: Dockerfile
    hostname: glpi
    volumes:
      - "${GLPI_PATH}/html:/var/www/html"
    container_name: "${GLPI_NAME}_glpi"
    links:
      - mysql:mysql
    ports:
      -  "${GLPI_HTTP_IP_PORT}:80"
    depends_on:
      - mysql
    restart: always
    logging:
      driver: none
